apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis

spec:
  selector:
    matchLabels:
      app: redis  # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: redis
    spec:
      schedulerName: stork
      containers:
      - name: redis
        image: redis:3.2-alpine
        imagePullPolicy: Always
        args: ["--requirepass", "$(REDIS_PASS)"]
        ports:
          - containerPort: 6379
            name: redis
        env:
        - name: REDIS_PASS
          value: password
        volumeMounts:
          - name: redis-vol
            mountPath: /data
      volumes:
      - name: redis-vol
        persistentVolumeClaim:
          claimName: px-redis-pvc